### ISSUE TITLE
Introduction screen with simple instructions

### ISSUE THREAD

**Issue by tnordberg** [scimusmn/tg-inheritance-game#10]

**Comment by bryankennedy** [comment]
Manuel, Trygve says you're working on this. Let me know if not and I'll reassign.

**Comment by bryankennedy** [comment]
@calym I think you've been working on this for the variation game. Can you confirm?

**Comment by calym** [comment]
This is done, though will eventually include an audio file that reads the instructions. That should probably be a separate issue. Or maybe two, one for creating the asset and one for adding it. Do we know who will be recording it?

**Comment by bryankennedy** [comment]
I agree it makes sense to detail those issues in another issue. I added that here: #30
