### ISSUE TITLE
Touch interface and animation for rapidly swiping image cards left or right

### ISSUE THREAD

**Issue by tnordberg** [scimusmn/tg-inheritance-game#11]

**Comment by tnordberg** [comment]
We are holding off on worrying about a touch interface based on our last design conversation. (We may not need it)

**Comment by bryankennedy** [comment]
@calym let's touch base on whether this is part of your work on the `pigeon tinder` game.

**Comment by bryankennedy** [comment]
@calym I think this got switched to a keyboard interface right? I assume we don't need the swipe gesture any longer. Do I have that right?

**Comment by calym** [comment]
Yes, it has a left-right animation but uses arrow keys and not a touch screen.

**Comment by bryankennedy** [comment]
Can you close this if that's fully done now?

**Comment by bryankennedy** [comment]
Closing for now. Reopen if that's premature.
