### ISSUE TITLE
Source and resize final images for consistent shape and resolution

### ISSUE THREAD

**Issue by tnordberg** [scimusmn/tg-inheritance-game#14]

**Comment by tnordberg** [comment]
Kathy has already gathered images that work, but we'll need to check them for resolution.

**Comment by tnordberg** [comment]
Sarah Z. and Kathy G. will be handling this.

**Comment by bryankennedy** [comment]
I'm going to mark this done for now, since I think it's more of an ongoing process issue. Let's create some more specific issues for any groups of media assets that we need.
