### ISSUE TITLE
End of game screen displaying results and next action to take

### ISSUE THREAD

**Issue by tnordberg** [scimusmn/tg-inheritance-game#15]

**Comment by bryankennedy** [comment]
Manuel, Trygve says you're working on this. Let me know if not and I'll reassign.

**Comment by bryankennedy** [comment]
Still active?

**Comment by calym** [comment]
It exists but still needs styling.

**Comment by tnordberg** [comment]
Removing myself. Caly is handling this.

**Comment by bryankennedy** [comment]
Issue moved to [scimusmn/infestation #31](https://github.com/scimusmn/infestation/issues/31) via [**ZenHub**](https://www.zenhub.com/)
