### ISSUE TITLE
Display an ordered series images, centered, one at a time.

### ISSUE THREAD

**Issue by tnordberg** [scimusmn/tg-inheritance-game#3]

**Comment by calym** [comment]
@bryankennedy this is for inheritance and not variation, should it be closed?

**Comment by bryankennedy** [comment]
Hmm, I'm not sure. @tnordberg I moved this to closed since it was in the Done column since last Oct. Is this still active?

**Comment by tnordberg** [comment]
This was completed as part of the prototype. We can close.
