### ISSUE TITLE
Restart application with reset button press, or on timeout

### ISSUE THREAD

**Issue by tnordberg** [scimusmn/tg-inheritance-game#9]

**Comment by bryankennedy** [comment]
Manuel, Trygve says you're working on this. Let me know if not and I'll reassign.

**Comment by bryankennedy** [comment]
Is this still active?

**Comment by calym** [comment]
Yeah, this still needs to be done.

**Comment by tnordberg** [comment]
Removing myself from this task. Caly is on it.

**Comment by bryankennedy** [comment]
Issue moved to [scimusmn/infestation #32](https://github.com/scimusmn/infestation/issues/32) via [**ZenHub**](https://www.zenhub.com/)
